### ISSUE TITLE
User Stories #9 - Login

### ISSUE THREAD

**Issue by charityml** [vcu-cmsc355-f17/android-app-array-51#10]
Alwin: “As a small business manager, so that I can avoid pranks and problems, I want to have the app be password protected.”

testValidLogin
Given I am on the login screen
When I enter the correct username and password
Then I should be transferred to the welcome page

testInvalidLogin
Given I am on the login screen
When I enter the incorrect username and password
Then I should be prompted that an incorrect username and password was submitted.

testInfoPopUp
Given I am on the login screen
When I enter the correct username and password
Then I should be prompted with notifications of schedule and availability submissions.

**Comment by AlwinHollebrandse** [comment]
added test names
